model:
  model_id: tekken_rft_v2
  sample_size: [14, 23]
  channels: 128
  n_buttons: 8
  n_layers: 16
  n_heads: 16
  d_model: 2048

  tokens_per_frame: 322
  n_frames: 2048
  has_audio: false

  cfg_prob: 0.2
  causal: true
  uncond: false
  backbone: dit

  # rope_impl: motion
  # rope_ats_delta: 2.0

  local_window: 8
  global_window: 128

train:
  trainer_id: tekken_rft_v2
  data_id: tekken_multi_v2
  data_kwargs:
    window_length: 128 # 256
    temporal_compression: 1
    root_dir: /mnt/data/laplace/datasets/rgb_latents_t3vae

  sample_data_id: tekken_multi_v2
  sample_data_kwargs:
    window_length: 32  # size of single ground truth start tokens
    temporal_compression: 1
    root_dir: /mnt/data/laplace/datasets/rgb_latents_t3vae

  scheduler: null

  target_batch_size: 8
  batch_size: 1
  compile: true

  epochs: 10000

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys: [core.proj_in, core.proj_out.proj, core.t_embed, core.action_embed, gate, adaln]

  checkpoint_dir: /mnt/data/laplace/owl-wms/checkpoints/combat_v0_t3vae_L
  output_path: /mnt/data/laplace/owl-wms/checkpoints/combat_v0_t3vae_L_ema
  resume_ckpt: null

  sample_interval: 5000
  save_interval: 10000          

  sampler_id: t3_action_caching
  sampler_kwargs:
    n_steps: 32
    cfg_scale: 1.0
    num_frames: 192
    noise_prev: 0.2
    only_return_generated: false
  # num_seed_frames: 60

  vae_id: null
  vae_cfg_path: "preproccessing/checkpoints/t3_VAE_nopose_v1/config.yaml" #null # Path to your VAE config
  vae_ckpt_path: "/mnt/data/laplace/owl-wms/preproccessing/checkpoints/t3_VAE_nopose_v1/step_49000.pt" # Path to your VAE checkpoint
  vae_scale: 1.0 
  vae_batch_size: 8
  n_samples: 2
  eval_sample_dir: null


wandb:
  name: d-fusion  # lapp0-andrew-lapp
  project: COMBAT-WM  # owl
  run_name: combat_v0_t3vae_L
