model:
  model_id: game_rft

  channels: 16  # 128

  n_layers: 20
  n_heads: 16
  d_model: 2048

  n_frames: 512

  tokens_per_frame: 390
  height: 15
  width: 26
  patch_size: [1, 4, 4]

  has_audio: false

  n_buttons: 11
  n_mouse_axes: 2

  cfg_prob: 0.1

  causal: true
  uncond: true
  backbone: dit
  rope_impl: motion
  rope_ats_delta: 2.0

  local_window: 16
  global_window: 16  # only 32 for WAN sampling (81 frames total)

train:
  trainer_id: rft_pair_distill
  data_id: wan_pair_distill
  data_kwargs:
    dataset_path: /mnt/data/lapp0/datasets/wan_generated/
    batch_columns: ["x_a", "time_a", "x_b", "time_b", "x_clean", "time_clean"]

  sample_data_id: wan_sample
  sample_data_kwargs:
    window_length: 10  # size of single ground truth start tokens
    dataset_path: /mnt/data/lapp0/datasets/wan_generated/
    batch_columns: ["x"]

  finite_difference_step: 2000

  target_batch_size: 64
  batch_size: 4

  epochs: 10000

 # opt: AdamW
 # opt_kwargs:
 #   lr: 1.0e-4
 #   weight_decay: 1.0e-4
 #   eps: 1.0e-15
 #   betas: [0.9, 0.95]
  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys: [core.proj_in, core.proj_out.proj, core.t_embed, gate, adaln]
    # TODO: control_embed needed for joint training eventually, dont optimize with muon

  scheduler: null

  checkpoint_dir: checkpoints/video_dit_v4
  output_path: /mnt/data/owl-wms/checkpoints/dit_v4
  resume_ckpt: null

  sample_interval: 1000
  save_interval: 10000

  sampler_id: av_caching
  sampler_kwargs:
    n_steps: 16
    cfg_scale: 1.0
    num_frames: 200
    noise_prev: 0.2
    only_return_generated: false

  n_samples: 4
  eval_sample_dir: null

  vae_id: null
  vae_batch_size: 4

  # UNUSED IN WAN
  # vae_scale: 0.63
  # vae_cfg_path: /mnt/data/shahbuland/owl-vaes/configs/cod_yt_v2/base.yml
  # vae_ckpt_path: /mnt/data/checkpoints/owl_vaes/cod_yt_v2/cod_yt_v2_515k_ema_decoder.pt

wandb:
  name: louiscastricato  # lapp0-andrew-lapp
  project: video_models  # owl
  run_name: video_dit_v4
