# Config for a simple 256 -> 16 autoencoder
model:
  model_id: titok_vq
  sample_size: 64
  channels: 3
  latent_size: 16
  latent_channels: 16
  codebook_size: 1024

  noise_decoder_inputs: 0.0

  n_layers: 12
  n_heads: 6
  d_model: 384

  patch_size: 4

train:
  trainer_id: rec
  data_id: mnist

  target_batch_size: 32
  batch_size: 32

  epochs: 200

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 0.01
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys:
      [encoder.proj_in, encoder.proj_out, decoder.proj_in, decoder.proj_out]

  loss_weights:
    latent_reg: 0.0
    lpips: 0.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 100
    min_lr: 1.0e-4

  checkpoint_dir: checkpoints/v0

  sample_interval: 1000
  save_interval: 10000

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: v0
